### ISSUE TITLE
v.0.2.4 ?

### ISSUE THREAD

**Issue by Yaroslav-F** [ankane/distribute_reads#14]
Hi Andrew

First of all, thanks for this gem, seems to be exactly what I was looking for.
I'm planning to make it work with Aurora mysql read replicas so it seems like https://github.com/ankane/distribute_reads/commit/3cf0151b4e5e7eeaefab39ee3aaebf18e5c7edeb will be massively helpful.
I'm probably going to use the master branch for now, but are there any plans to release v.2.4 that will include Aurora fix along with other typo fixes I noticed in master branch commits?

Thanks

**Comment by ankane** [comment]
Hey @Yaroslav-F, I don't have specific plans of when the next version will be released. Pinning your Gemfile to a specific commit should work fine.
