### ISSUE TITLE
distribute_reads not query from replica when query has bracket

### ISSUE THREAD

**Issue by icecold21** [ankane/distribute_reads#17]
Hi Ankane, great gem btw, 

I was wondering why query which has bracket arounds it goes to primary instead of replica.
These are code to repro the issue:

### Query to replica
```
distribute_reads do
  ActiveRecord::Base.connection.execute("SELECT 1")
end
```

### Query to primary
```
distribute_reads do
  ActiveRecord::Base.connection.execute("(SELECT 1)")
end
```

**Comment by ankane** [comment]
Hey @icecold21, Makara uses regular expressions to determine which queries can go to replicas. You can force the query to use a replica with `distribute_reads(replica: true)`.

**Comment by icecold21** [comment]
Hi @ankane, thanks for the answer. I'll go ahead and close this issue.
