### ISSUE TITLE
AWS RDS replica lag negative one doesn't cause failover

### ISSUE THREAD

**Issue by njfix6** [ankane/distribute_reads#26]
In AWS RDS, it is possible to have negative one replica lag, which means the replica is up but not replicating. I think the distribute reads should also failover in this case.

**Comment by njfix6** [comment]
Will work on a PR soon.

**Comment by njfix6** [comment]
Added a PR here: https://github.com/ankane/distribute_reads/pull/27

**Comment by ankane** [comment]
Thanks, let's have any follow up discussion in the PR.
