### ISSUE TITLE
Crash with makara 0.6.0-pre

### ISSUE THREAD

**Issue by dvandersluis** [ankane/distribute_reads#45]
Hi, I'm getting an error when using `distribute_reads` with makara 0.6.0-pre:

```
NoMethodError: undefined method `needs_master?' for #<Makara::ConnectionWrapper:0x0000565201a48e28 ...>
(eval):36:in `public_send'
(eval):36:in `block in exec_query'
(eval):16:in `_makara_hijack'
(eval):34:in `exec_query'
```

**Comment by ankane** [comment]
Hey @dvandersluis, prerelease versions of Makara aren't supported, but you can try the `edge` branch - see #44.

**Comment by dvandersluis** [comment]
@ankane thanks -- I'd rather not use a prerelease version either but it's the only one that fixes for ruby 3 syntax :/
