### ISSUE TITLE
Question: Is this effectively a `Makara.stick_to_replica!`

### ISSUE THREAD

**Issue by lloydwatkin** [ankane/distribute_reads#52]
Hi, I'm just trying to fully understand this gem before implementing. 

If I were to set **sticky: true** in my `database.yml` but wanted to force reads to go to a replica, is this where this gem effectively comes in? Or is there more to it than that?

Thanks!

**Comment by ankane** [comment]
Hey @lloydwatkin, I'm not sure I understand the question, but check out the readme for how it works (or try it out).
