### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by tdeo** [ankane/distribute_reads#6]
Hi,

I'd be interested in using https://github.com/ankane/distribute_reads/commit/7168dde99dd4071ee305957dcf068df0189026a9 to force some reads to go to a slave (to check on replication delay with a custom implementation, since MySQL's `Seconds_Behind_Master` doesn't seem very reliable from their doc).

Did you have a release planned any time soon?

**Comment by ankane** [comment]
Hey @tdeo, new release pushed.

**Comment by tdeo** [comment]
Thanks
