### ISSUE TITLE
It was too easy

### ISSUE THREAD

**Issue by vassilevsky** [ankane/distribute_reads#9]
Hi :)

So I installed this gem, configured `database.yml`, wrapped some slow code in `distribute_reads` block, and it just works. I see `[master/1]` and `[slave/1]` in the logs. Queries just go to different databases. Nothing is breaking. I see no weird errors. Nothing pops up in Sentry. And this is all on Rails 3.2, I might add.

I feel like there's a catch somewhere.

Is this supposed to be that easy?

I'm getting nervous.

**Comment by vassilevsky** [comment]
OK I had one issue: Sidekiq couldn't find newly created records by id on the replica because lag.

Phew.

**Comment by ankane** [comment]
Ha, sounds about right. Glad it was easy to use :)
